name: WILLIAIKUMA
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3.2
  - asttokens=2.0.5
  - atk-1.0=2.36.0
  - attr=2.4.48
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - dbus=1.13.18
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - fontconfig=2.14.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.8
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.74.0
  - glib-tools=2.74.0
  - graphite2=1.3.14
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gtk2=2.24.33
  - harfbuzz=2.9.1
  - icu=68.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipython=8.4.0
  - jack=1.9.18
  - jedi=0.18.1
  - jpeg=9e
  - json-c=0.13.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcap=2.36
  - libdb=6.2.32
  - libdeflate=1.8
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=12.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.74.0
  - libglu=9.0.0
  - libiconv=1.17
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.37
  - libsndfile=1.0.31
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.10
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openssl=3.0.5
  - pango=1.42.4
  - parso=0.8.3
  - pathlib2=2.3.6
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - portaudio=19.6.0
  - prompt-toolkit=3.0.20
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio=13.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pypubsub=4.0.3
  - pysocks=1.7.1
  - pysoundfile=0.11.0
  - python=3.9.13
  - python-sounddevice=0.4.1
  - python_abi=3.9
  - readline=8.2
  - requests=2.28.1
  - scipy=1.9.1
  - setuptools=65.4.0
  - six=1.16.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tk=8.6.12
  - traitlets=5.1.1
  - tzdata=2022e
  - urllib3=1.26.12
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wxpython=4.1.1
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - natsort==8.2.0
      - praatio==5.1.1
      - pyaudio==0.2.12
      - pydub==0.25.1
      - pympi-ling==1.70.2
      - simpleaudio==1.0.4
      - tkinter-fonts-viewer==0.1.2
      - typing-extensions==4.4.0
